services:
  - type: web
    name: spiderfoot
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: python3 ./sf.py -l 0.0.0.0:$PORT -max-threads 2 -x
    disk:
      name: spiderfoot-data
      mountPath: /root/.spiderfoot
      sizeGB: 2
